# --- Model Sequence ---
model:
  name: "FusionModel"
  embed_dim: 128
  sequence_processor: "resnet" # Options: resnet, transformer

training:
  batch_size: 32
  learning_rate: 3.0e-4
  weight_decay: 1.0e-5
  num_epochs: 50
  patience: 5
  optimizer: "adam"
  lr_schedule: "cosine"
  n_repeats: 10